### ISSUE TITLE
"Points Per Cycle" Chat Messages Even With Random Items Disabled

### ISSUE THREAD

**Issue by TheVisionaryOne** [ghzdude/MCRandomizer#13]
I've noticed that the "points per cycle" messages still appear in chat when the Random Items module is disabled.

This is obviously a very minor inconvenience, especially for anybody who's simply playing by themselves. However, it becomes a little more confusing when it has to be explained to multiple people, especially in larger numbers. For example on a multiplayer server or a Twitch stream.

**Comment by ghzdude** [comment]
this should be fixed with 26502ed2ce8e6ee9b0f41a74b0ca93693e49c300, and i'll be releasing another version sometimes soon
