### ISSUE TITLE
Crash on Game Start (0.8a)

### ISSUE THREAD

**Issue by TheVisionaryOne** [ghzdude/MCRandomizer#20]
I've loaded up version 0.8a to test, and it crashes on game start with the message "MC Randomizer has failed to load correctly."

![javaw_1eisbJbMDA](https://github.com/user-attachments/assets/614fd6eb-a72b-4ec2-b06b-36131e94fe95)

I've attached the crash report here:
[crash-2024-12-13_15.56.13-fml.txt](https://github.com/user-attachments/files/18132973/crash-2024-12-13_15.56.13-fml.txt)

I'm running the latest version of Forge (51.0.33).

**Comment by ghzdude** [comment]
ah, the mod has been updated to use Forge 52.0.28, which had a breaking change involving mod constructors causing 1.21 and 1.21.1 to not work

**Comment by ghzdude** [comment]
actually, it's just the latest forge for 1.21 that doesn't work, 1.21.1+ can use Forge 52.0.28

**Comment by ghzdude** [comment]
fixed in 0.8b
