### ISSUE TITLE
Speedrun Viability Config Option (Feature Request)

### ISSUE THREAD

**Issue by TheVisionaryOne** [ghzdude/MCRandomizer#21]
I just tried to do a survival speedrun with random crafting recipes enabled, only to realize after playing for 3 hours that there was no recipe assigned to Ender Eyes. This made it technically impossible to beat the game while in survival.

Obviously this kind of stuff is to be expected when playing with a randomizer. However, it would be nice if there was some sort of "survival mode" or "speedrun" config option that guarantees Ender Eyes are craftable. This feature would only be necessary for the crafting recipe randomizer.

I'm no modder, but I have a couple of ideas on ways this could be implemented:
- An "item priority" whitelist. Any item added on this whitelist is assigned a recipe before recipes are randomized.
- A process that checks the ender eye recipe on world load, and prints a chat message (e.g. WINNABLE, NOT WINNABLE).

If this feature request is not possible, or too big of an undertaking, that's completely understandable.

**Comment by ghzdude** [comment]
implemented in 0.8b

**Comment by TheVisionaryOne** [comment]
Thanks for implementing this, it has been wonderful! I've done 4+ speedruns and it works like a charm. Awesome stuff!
