### ISSUE TITLE
reset the randomizer

### ISSUE THREAD

**Issue by flauschiyt** [ghzdude/MCRandomizer#4]
Hello, is it possible to reset it? so that there will come other items?

**Comment by ghzdude** [comment]
I assume you mean to make the randomizer re-run, in which case you should be able to delete `randomizer_` .dat files within the world/save folder. However, i think the randomizer might be using the world seed as rng, so it might not appear to be different. I might make a config to not use the world seed if it doesn't already.

**Comment by ghzdude** [comment]
gonna close this as it's stale.
