### ISSUE TITLE
1.21 Crash on Startup

### ISSUE THREAD

**Issue by TheVisionaryOne** [ghzdude/MCRandomizer#7]
When running the new 1.21 version of MCRandomizer, the game crashes on startup.

The error log says: "Caused by: org.apache.maven.artifact.versioning.InvalidVersionSpecificationException: Range cannot have identical boundaries: (1.21,1.21)"

Crash Log:
https://mclo.gs/oWCw6wl

**Comment by TheVisionaryOne** [comment]
It seems like this error is referring to this line in gradle.properties. Seems like a relatively quick fix, whenever you have time to patch it.
![chrome_zJceAdVyBi](https://github.com/user-attachments/assets/f5c018f8-0473-493b-8881-6bda6cdf094f)

**Comment by ghzdude** [comment]
strange how the dev env doesn't care about the version range, but it should be fixed now
