### ISSUE TITLE
1.21 Loot/Recipe Randomizers Are Broken

### ISSUE THREAD

**Issue by TheVisionaryOne** [ghzdude/MCRandomizer#9]
All randomizers seem to be completely broken except for the Random Item Giver and Random Mob Spawner. Even when enabled in the config, none of the other randomizers (such as random block loot) seem to do anything. This issue seems to only be present in the 1.21 version of this mod.

Minecraft Version: 1.21
Mod Version: 0.6c (latest)
Forge Version: 51.0.26

**Comment by ghzdude** [comment]
I'm not able to reproduce the issues with the Loot Randomizer.

**Comment by ghzdude** [comment]
okay, to be more precise, i can't reproduce in dev. i tried using the latest version of the mod "0.6d" and it wasn't working for some reason

**Comment by ghzdude** [comment]
there was a recent change in Forge where mixins weren't applying in production but was fine in dev. i've actually fixed it now.

**Comment by TheVisionaryOne** [comment]
Sweet! Glad to see it up and fully working on 1.21.

Love this mod, and I appreciate the work you've done to keep it up to date with newer versions!
